import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import Footer from "@/components/Footer";
import Logo from "@/components/Logo";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
				<div className="container relative bg-gray-900 mx-auto">
					<div className="px-8 py-8 z-10 top-0 left-0 sticky flex justify-between">
						<Logo home={true} />
						<NavBar />
					</div>
					{children}
					<div className="bottom-0 sticky py-4">
						<Footer />
					</div>
				</div>
			</body>
		</html>
	);
}
